"""Generate an accuracy declaration (EU AI Act Annex IV §6 / Art. 15).

Runs the eval harness on a holdout dataset and renders a Markdown accuracy
declaration ready to drop into
``docs/eu_ai_act/annex_iv_technical_documentation.md`` §6. The *measured* metrics
are filled in from the run; provenance and sign-off remain ``TODO`` because they
require human/legal input — the generator never fabricates those.

Usage::

    python -m cats.calibration.report \\
        --dataset holdout.jsonl --weights calibrated_weights.json \\
        --out docs/eu_ai_act/accuracy_declaration.md
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from cats.calibration.dataset import load_dataset
from cats.calibration.evaluate import EvalReport, evaluate_dataset, load_weights_file, static_weights_for
from cats.calibration.objective import make_groups


def render_declaration(report: EvalReport, *, dataset: str, generated: str) -> str:
    """Render an Annex IV §6 / Art. 15 accuracy declaration as Markdown."""
    band_rows = "\n".join(
        f"| {r.band} | {r.count} | {r.mean_predicted:.1f} | {r.mean_label:.1f} |" for r in report.bands
    )
    group_rows = "\n".join(
        f"| {g.source_type} | {g.count} | "
        f"{g.spearman if g.spearman is not None else 'n/a'} | "
        f"{g.concordance if g.concordance is not None else 'n/a'} |"
        for g in report.per_source_type
    )
    return f"""# CATS — Accuracy Declaration (EU AI Act Annex IV §6 / Art. 15)

> Auto-generated by `cats.calibration.report` from a holdout evaluation.
> ⚠️ **Not legal advice.** Measured metrics are filled in; provenance and
> sign-off are `TODO` (human/legal input). See
> [annex_iv_technical_documentation.md](annex_iv_technical_documentation.md) §6.

| Field | Value |
|---|---|
| Generated (UTC) | {generated} |
| Holdout dataset | `{dataset}` |
| Samples (n) | {report.n} |
| Weights | {report.weights_source} |

## Measured accuracy (rank agreement)

CATS scores are **ordinal** (WP 4.3), so accuracy is measured as rank agreement
between predicted scores and ground-truth labels, not absolute error.

| Metric | Value |
|---|---|
| Spearman rank correlation | **{report.spearman:+.3f}** |
| Pairwise concordance (AUC-like) | **{report.concordance:.3f}** |
| Band agreement (exact) | {report.band_agreement_exact:.1%} |
| Band agreement (within 1 band) | {report.band_agreement_adjacent:.1%} |

> v2.0 target: AUC-ROC ≥ 0.78 on a labelled OSINT dataset. Pairwise concordance
> above is the AUC-like analogue for ordinal labels.

### Per predicted band

| Band | n | Mean predicted | Mean label |
|---|---|---|---|
{band_rows}

### Per source type

| Source type | n | Spearman | Concordance |
|---|---|---|---|
{group_rows}

## Conditions & caveats

- Holds under the holdout distribution above; generalisation to other source
  mixes/languages is not implied (Italian-optimised NLP — WP 4.1).
- Default NLP accuracy ~55–62% unless BERT/Sentence-BERT backends are enabled.
- Band **thresholds** are not themselves calibrated (WP 4.1); only the
  aggregation weights are.

## TODO (human / legal)

- [ ] Dataset provenance and labelling methodology (link to data governance).
- [ ] Labelling strategy (expert / distant supervision) and inter-annotator agreement.
- [ ] Confirm temporal train/holdout split and dates.
- [ ] Sign-off (name, role, date).
"""


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m cats.calibration.report",
        description="Generate an EU AI Act Art. 15 accuracy declaration from a holdout evaluation.",
    )
    parser.add_argument("--dataset", required=True, type=Path, help="holdout calibration dataset (.jsonl/.json)")
    parser.add_argument("--weights", type=Path, default=None, help="calibrated weights file; omit for static estimates")
    parser.add_argument("--out", type=Path, default=None, help="write Markdown here (default: stdout)")
    args = parser.parse_args(argv)

    if not args.dataset.exists():
        parser.error(f"dataset not found: {args.dataset}")

    samples = load_dataset(args.dataset)
    groups = make_groups(samples)
    if args.weights is not None:
        if not args.weights.exists():
            parser.error(f"weights file not found: {args.weights}")
        weights = load_weights_file(args.weights, groups)
        source = str(args.weights)
    else:
        weights = static_weights_for(groups)
        source = "static (WP 4.1 estimates)"

    report = evaluate_dataset(samples, weights, weights_source=source)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    md = render_declaration(report, dataset=str(args.dataset), generated=generated)

    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(md, encoding="utf-8")
        print(f"Wrote accuracy declaration to {args.out}")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
